# -*- coding: utf-8 -*-
"""Client Segmentation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hz1-eHcxwUraFgwzAIJXx8f70YK8Fom2
"""

# @title Default title text
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import normalize
import scipy.cluster.hierarchy as shc

# Read the data from CSV file
data = pd.read_csv('Wholesale customers data.csv')
print(data.head())
# Normalize the data
data_scaled = normalize(data)
data_scaled = pd.DataFrame(data_scaled, columns=data.columns)
print(data_scaled.head())

# Generate Dendrogram
plt.figure(figsize=(10, 7))
plt.title("Dendrograms")
dend = shc.dendrogram(shc.linkage(data_scaled, method='ward'))
plt.axhline(y=6, color='r', linestyle='--')

from sklearn.cluster import AgglomerativeClustering
cluster = AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='ward')
cluster.fit_predict(data_scaled)

plt.figure(figsize=(10, 7))
plt.scatter(data_scaled['Milk'], data_scaled['Grocery'], c=cluster.labels_)